@baseUrl = http://localhost:8080/api

####
DELETE {{baseUrl}}/listings/molestiae_dignissimos_


####
POST {{baseUrl}}/listings
Content-Type: application/json
Authorization: Basic admin 123

{
    "title": "Titulo 1",
    "categories": [
       "http://localhost:8080/categories/1",
       "http://localhost:8080/categories/2"
   ]
}

#####

GET {{baseUrl}}/listings/

####

PUT http://localhost:8080/api/accounts/1
Content-Type: application/json
Authorization: Basic admin 123

{
  "username": "oaisdfjaoifij"
}

### Registration

POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Loja 1",
    "email": "email@gmail.com"
}


####

POST {{baseUrl}}/stores/1/accounts
Content-Type: application/json

{
    "name": "test"
}
