@baseUrl = http://localhost:8080/api


####

GET {{baseUrl}}/profile/listings


####
GET {{baseUrl}}/categories/6/
Authorization: Basic STORE_OWNER 123

####
POST {{baseUrl}}/listings
Content-Type: application/json

{
    "title": "Titulo 1",
    "categories": [
       "http://localhost:8080/categories/1",
       "http://localhost:8080/categories/2"
   ]
}

####

POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Basic STORE_OWNER 123

{
    "name": "eita 123",
    "username": "oloco 123",
    "email": "diego@test.com",
    "password": "oloco",
    "role": "STORE_OWNER",
    "store": "{{baseUrl}}/stores/1"
}

####

GET {{baseUrl}}/accounts

### Registration

POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "Loja 1",
    "email": "email@gmail.com"
}


####

POST {{baseUrl}}/stores/1/accounts
Content-Type: application/json

{
    "name": "test"
}
