spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:marketplace
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true