spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:file:./marketplace;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy