spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/marketplace
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy