spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
    datasource:
        url: jdbc:mysql://localhost:3306/marketplace
        username: root
        password: 123
        driver-class-name: org.mariadb.jdbc.Driver
    data:
        rest:
            base-path: /api
            default-page-size: 10
            detection-strategy: annotated
            return-body-on-create: true