spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming:
                  strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        show-sql: true
        generate-ddl: true
    datasource:
        url: jdbc:mysql://localhost:3306/marketplace
        username: root
        password: 123
        driver-class-name: org.mariadb.jdbc.Driver